---
dist: xenial
sudo: required

language: python

services: []

before_install:
  - sudo apt install openssl -y
  - sudo pip install -U pip setuptools

install:
  - sudo pip install molecule==2.19 ansible==2.7.11
  - ansible --version
  - molecule --version

script:
  - molecule test
