---
dist: xenial
sudo: required

language: python

services: []

before_install:
  - deactivate
  - sudo apt-get update -qq

install:
  - sudo pip install molecule
  - ansible --version
  - molecule --version

script:
  - molecule test
