---
# tasks file for ansible-systemd-docker

- name: install docker and required packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ packages }}'
  when: install_os_deb_version | bool
  tags:
    - install
    - docker

- name: install docker python module
  pip:
    name: "{{ pip_packages }}"
    state: present
  tags:
    - install
    - docker

- debug: var=item verbosity=4
  with_items: '{{ docker_apps }}'
  tags:
    - debug

- name: template docker app systemd
  template:
    src: docker-app.service.j2
    dest: "/etc/systemd/system/{{ systemd_unit_prefix }}{{ item.name }}{{ systemd_unit_postfix }}.service"
    owner: root
    group: root
    mode: 0644
    backup: true
  notify: reload systemd
  with_items: '{{ docker_apps }}'
  when:
    - item.container
    - item.url is not defined
  tags:
    - template

- name: pull down custom docker app systemd files
  get_url:
    url: "{{ item.url }}"
    dest: "/etc/systemd/system/{{ systemd_unit_prefix }}{{ item.name }}{{ systemd_unit_postfix }}.service"
    owner: root
    group: root
    mode: 0644
    backup: true
    checksum: "{{ item.checksum | default(omit) }}"
  notify: reload systemd
  with_items: '{{ docker_apps }}'
  when: item.url is defined
  tags:
    - template

- meta: flush_handlers
  tags:
    - template

- name: make source directories
  file:
    path: '{{ item.1.src }}'
    state: directory
    mode: 0755
    owner: "{{ item.1.owner | default('root') }}"
    group: "{{ item.1.group | default('root') }}"
  with_subelements:
    - '{{ docker_apps }}'
    - volumes
  when: make_dirs
  failed_when: false
  tags:
    - template
    - mkdir

- name: pull down extra files
  get_url:
    url: "{{ item.1.src }}"
    dest: "{{ item.1.dest }}"
    owner: root
    group: root
    mode: 0644
    force: true
  with_subelements:
    - '{{ docker_apps }}'
    - files_to_dl
  when: item.1.src is defined
  tags:
    - template
    - mkdir

- name: start docker service
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  with_items:
    - docker
  tags:
    - docker

- name: reload all systemd units
  systemd:
    daemon_reload: true
  tags:
    - docker

# - name: pull down all containers
#   docker_image:
#     name: "{{ item.container }}"
#     # added in 2.8
#     # source: pull
#   with_items: '{{ docker_apps }}'
#   register: docker_pull
#   until: docker_pull | succeeded
#   tags:
#     - docker

- name: pull down all containers
  command: docker pull {{ item.container }}
  with_items: '{{ docker_apps }}'
  register: docker_pull
  until: docker_pull.rc == 0
  failed_when: false
  changed_when: false
  tags:
    - docker

- name: start the docker apps
  systemd:
    name: "{{ systemd_unit_prefix }}{{ item.name }}{{ systemd_unit_postfix }}.service"
    state: "{{ item.state | default('started') }}"
    enabled: "{{ item.enabled | default(true) }}"
  with_items: '{{ docker_apps }}'
  tags:
    - docker
