---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: systemd-localhost
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - prepare
    - lint
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
Scenario: 'default'
verifier:
  name: ansible
